export enum IssueStatus {
  REPORTED = 'REPORTED',
  IN_PROGRESS = 'IN_PROGRESS',
  ASSIGNED_TO_SUPERVISOR = 'ASSIGNED_TO_SUPERVISOR',
  ASSIGNED_TO_WORKER = 'ASSIGNED_TO_WORKER',
  WORK_COMPLETED = 'WORK_COMPLETED',
  RESOLVED = 'RESOLVED',
  MANUAL_REVIEW = 'MANUAL_REVIEW',
}
